import type { DailyBiometricRecord, UserBaseline } from '@/types/wearables';

/** Factory for a fully-null UserBaseline. */
export function makeBaseline(overrides: Partial<UserBaseline> = {}): UserBaseline {
  return {
    userId: 'user-001',
    updatedAt: '2026-07-01T00:00:00Z',
    hrv7Day: null,
    hrv14Day: null,
    hrv30Day: null,
    restingHr7Day: null,
    restingHr14Day: null,
    restingHr30Day: null,
    sleepDuration7Day: null,
    sleepDuration14Day: null,
    sleepDuration30Day: null,
    sleepEfficiency7Day: null,
    sleepEfficiency14Day: null,
    sleepEfficiency30Day: null,
    steps7Day: null,
    steps14Day: null,
    steps30Day: null,
    respiratoryRate7Day: null,
    respiratoryRate14Day: null,
    tempDeviation7Day: null,
    tempDeviation14Day: null,
    bedtimeAvg: null,
    wakeTimeAvg: null,
    weight7Day: null,
    weight30Day: null,
    ...overrides,
  };
}

/**
 * Factory for a fully-null DailyBiometricRecord. Override only the fields a
 * test cares about.
 */
export function makeRecord(overrides: Partial<DailyBiometricRecord> = {}): DailyBiometricRecord {
  return {
    id: 'rec-001',
    userId: 'user-001',
    source: 'oura',
    date: '2026-07-01',
    sleepDurationMinutes: null,
    sleepEfficiency: null,
    deepSleepMinutes: null,
    remSleepMinutes: null,
    lightSleepMinutes: null,
    sleepLatencyMinutes: null,
    wakeAfterSleepOnset: null,
    awakenings: null,
    sleepScore: null,
    bedtime: null,
    wakeTime: null,
    hrv: null,
    restingHr: null,
    avgHr: null,
    nighttimeHr: null,
    respiratoryRate: null,
    tempDeviation: null,
    skinTemp: null,
    readinessScore: null,
    stressScoreDevice: null,
    steps: null,
    distanceKm: null,
    caloriesBurned: null,
    activeMinutes: null,
    sedentaryMinutes: null,
    vo2Max: null,
    workoutMinutes: null,
    workoutType: null,
    trainingLoad: null,
    strainScore: null,
    weight: null,
    bodyFatPercent: null,
    spo2: null,
    glucoseAvg: null,
    bloodPressureSystolic: null,
    bloodPressureDiastolic: null,
    cyclePhase: null,
    cycleDayEstimate: null,
    hydrationMl: null,
    alcoholUnits: null,
    caffeineMg: null,
    caffeineLastTime: null,
    energyScore: null,
    stressScoreSubjective: null,
    sorenessScore: null,
    moodScore: null,
    libidoScore: null,
    bowelScore: null,
    cravingsScore: null,
    adherenceScore: null,
    subjectiveReadiness: null,
    symptomFlags: [],
    dataQualityScore: 0,
    ...overrides,
  };
}
