-- Peptide Library Seed Data (Part 1: Healing & Recovery)
INSERT INTO public.peptide_library (slug, name, aliases, category, description, mechanism, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, routes, forms, goals, stacking_notes, storage_notes, research_references, legal_note, wada_caution, clinician_only, pregnancy_safe, lactation_safe) VALUES
('bpc157', 'BPC-157', ARRAY['Body Protection Compound-157','Pentadecapeptide'], 'healing', 'Gastric pentadecapeptide that promotes wound healing, tendon repair, and gut mucosal protection.', 'Promotes angiogenesis, modulates nitric oxide system, enhances growth hormone receptor expression, and supports tendon/ligament healing through collagen synthesis.', 200, 500, 'mcg', 4, ARRAY['subcutaneous','intramuscular','oral'], ARRAY['lyophilized_vial','oral_capsule'], ARRAY['recovery','injury_rehab','metabolic_health'], 'Synergistic with TB-500 for tissue repair. Can be combined with GHK-Cu for enhanced healing.', 'Store reconstituted vials at 2-8°C. Stable for up to 30 days refrigerated.', '[{"title":"BPC-157 tissue healing mechanisms","type":"preclinical"}]', 'Research chemical. Not FDA approved for human use.', true, false, false, false),
('tb500', 'TB-500', ARRAY['Thymosin Beta-4','Tβ4'], 'healing', 'Thymosin beta-4 fragment promoting cell migration and tissue regeneration.', 'Promotes cell migration, blood vessel formation, and regulates actin for tissue repair and regeneration.', 2000, 5000, 'mcg', 2, ARRAY['subcutaneous','intramuscular'], ARRAY['lyophilized_vial'], ARRAY['recovery','injury_rehab','skin_health'], 'Pairs well with BPC-157 for comprehensive healing. Stagger injections by 30 min.', 'Store at 2-8°C after reconstitution. Use within 14 days.', '[{"title":"Thymosin Beta-4 wound healing","type":"preclinical"}]', 'Research chemical. Not FDA approved.', true, false, false, false),
('tb4_frag', 'TB-4 Fragment', ARRAY['Thymosin Beta-4 Fragment','Ac-SDKP'], 'healing', 'Active fragment of thymosin beta-4 with anti-fibrotic and tissue repair properties.', 'Anti-fibrotic and anti-inflammatory peptide fragment that promotes tissue repair without full TB-500 effects.', 200, 750, 'mcg', 1.5, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['recovery','injury_rehab'], 'Can substitute for TB-500 at lower doses. Stackable with BPC-157.', 'Store at 2-8°C. Use within 14 days of reconstitution.', '[{"title":"Ac-SDKP anti-fibrotic properties","type":"preclinical"}]', 'Research chemical.', true, false, false, false),
('bpc157_oral', 'BPC-157 Oral', ARRAY['Oral BPC','Oral Body Protection Compound'], 'healing', 'Oral formulation of BPC-157 for systemic gut healing and convenience.', 'Same mechanism as injectable BPC-157 but delivered orally for GI-focused healing with systemic absorption.', 250, 500, 'mcg', 4, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['recovery','metabolic_health'], 'Can be used alongside injectable BPC-157 for gut + local tissue targeting.', 'Store in cool dry place. No reconstitution needed.', '[{"title":"Oral BPC-157 bioavailability","type":"preclinical"}]', 'Research chemical. Not FDA approved.', false, false, false, false),
('kpv', 'KPV', ARRAY['Alpha-MSH Fragment','Lys-Pro-Val'], 'healing', 'Anti-inflammatory tripeptide derived from alpha-MSH with gut healing properties.', 'Inhibits NF-kB pathway, reduces pro-inflammatory cytokines, and promotes mucosal healing in the GI tract.', 200, 400, 'mcg', 2, ARRAY['subcutaneous','oral'], ARRAY['lyophilized_vial','oral_capsule'], ARRAY['recovery','immune_support'], 'Combines well with BPC-157 for gut healing protocols.', 'Store at 2-8°C.', '[{"title":"KPV anti-inflammatory effects","type":"preclinical"}]', 'Research chemical.', false, false, false, false),
('mgf', 'MGF', ARRAY['Mechano Growth Factor','IGF-1Ec'], 'healing', 'Splice variant of IGF-1 released by mechanically stimulated muscle tissue.', 'Activates muscle satellite cells, promotes local muscle repair and hypertrophy at injection site.', 100, 200, 'mcg', 0.5, ARRAY['intramuscular'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth','recovery','injury_rehab'], 'Inject locally at injury/target site. Can stack with PEG-MGF for extended action.', 'Store at -20°C lyophilized. Reconstituted: use immediately.', '[{"title":"MGF muscle repair mechanisms","type":"preclinical"}]', 'Research chemical.', true, false, false, false),
('ghk_cu', 'GHK-Cu', ARRAY['Copper Peptide','GHK-Copper'], 'skin', 'Copper-binding tripeptide with wound healing, anti-aging, and hair growth properties.', 'Stimulates collagen synthesis, promotes wound healing, has anti-inflammatory and antioxidant effects via copper delivery.', 1000, 2000, 'mcg', 1, ARRAY['subcutaneous','topical'], ARRAY['lyophilized_vial','cream'], ARRAY['skin_health','recovery','longevity'], 'Can be used topically for skin or injected for systemic collagen support.', 'Store at 2-8°C. Topical formulations stable at room temp.', '[{"title":"GHK-Cu skin regeneration","type":"RCT"}]', 'Available as cosmetic ingredient. Injectable is research chemical.', false, false, false, false),
('ghk', 'GHK', ARRAY['Glycyl-L-Histidyl-L-Lysine'], 'skin', 'Tripeptide without copper for topical skin rejuvenation.', 'Promotes collagen and elastin synthesis, supports skin remodeling and repair.', 1000, 2000, 'mcg', 1, ARRAY['topical'], ARRAY['cream'], ARRAY['skin_health'], 'Foundation of copper peptide topicals. Can combine with Matrixyl.', 'Stable at room temperature in formulation.', '[{"title":"GHK skin repair","type":"preclinical"}]', 'Cosmetic ingredient.', false, false, false, false)
ON CONFLICT (slug) DO NOTHING;

-- Part 2: GH Secretagogues
INSERT INTO public.peptide_library (slug, name, aliases, category, description, mechanism, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, routes, forms, goals, stacking_notes, storage_notes, research_references, legal_note, wada_caution, clinician_only, pregnancy_safe, lactation_safe) VALUES
('cjc1295_dac', 'CJC-1295 with DAC', ARRAY['CJC-1295 DAC','Drug Affinity Complex'], 'gh_secretagogue', 'Long-acting GHRH analog with Drug Affinity Complex for sustained GH release.', 'GHRH mimetic with DAC extension providing sustained GH release over 6-8 days per injection.', 1000, 2000, 'mcg', 144, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','muscle_growth','sleep','recovery','longevity'], 'Typically used alone due to long half-life. Do not stack with other GHRH analogs.', 'Store at 2-8°C. Stable 21 days reconstituted.', '[{"title":"CJC-1295 DAC pharmacokinetics","type":"RCT"}]', 'Research chemical. Prescription in some jurisdictions.', true, true, false, false),
('cjc1295_no_dac', 'CJC-1295 no DAC', ARRAY['Mod GRF 1-29','Modified GRF'], 'gh_secretagogue', 'Short-acting GHRH analog for pulsatile GH release mimicking natural patterns.', 'GHRH mimetic without DAC providing pulsatile GH release. Must be combined with a GHRP for optimal effect.', 100, 300, 'mcg', 0.5, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','muscle_growth','sleep','recovery'], 'Best combined with Ipamorelin or GHRP-2 for synergistic GH pulse. Inject together.', 'Store at 2-8°C. Use within 21 days of reconstitution.', '[{"title":"Mod GRF 1-29 GH release","type":"RCT"}]', 'Research chemical.', true, true, false, false),
('ipamorelin', 'Ipamorelin', ARRAY['IPA','Ipamorelin Acetate'], 'gh_secretagogue', 'Selective GH secretagogue that stimulates pulsatile GH release without cortisol or prolactin increase.', 'Ghrelin receptor agonist providing clean GH release without significant cortisol, prolactin, or hunger effects.', 200, 300, 'mcg', 2, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','muscle_growth','sleep','recovery','longevity'], 'Best paired with CJC-1295 no DAC. Gold standard GH secretagogue combo.', 'Store at 2-8°C. Reconstitute with bacteriostatic water.', '[{"title":"Ipamorelin selective GH release","type":"RCT"}]', 'Research chemical.', true, true, false, false),
('sermorelin', 'Sermorelin', ARRAY['GRF 1-29','Geref'], 'gh_secretagogue', 'Bioidentical GHRH fragment that stimulates natural GH production from the pituitary.', 'Binds GHRH receptors on pituitary somatotrophs to stimulate endogenous GH synthesis and release.', 200, 500, 'mcg', 0.2, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','sleep','recovery','longevity'], 'Can be combined with Ipamorelin. Good starter secretagogue.', 'Store at 2-8°C. Fragile peptide - handle gently.', '[{"title":"Sermorelin GH therapy","type":"RCT"}]', 'FDA approved for diagnostic use. Off-label for GH optimization.', true, true, false, false),
('tesamorelin', 'Tesamorelin', ARRAY['Egrifta','TH9507'], 'gh_secretagogue', 'FDA-approved GHRH analog for visceral fat reduction.', 'Synthetic GHRH analog that stimulates GH release, specifically studied for visceral adipose tissue reduction.', 1000, 2000, 'mcg', 0.4, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','metabolic_health'], 'Can be used as standalone. Do not combine with other GHRH analogs.', 'Store at 2-8°C. FDA-approved product with specific storage requirements.', '[{"title":"Tesamorelin visceral fat reduction","type":"RCT"}]', 'FDA approved (Egrifta) for HIV lipodystrophy.', true, true, false, false),
('hexarelin', 'Hexarelin', ARRAY['Examorelin'], 'gh_secretagogue', 'Potent GH secretagogue with cardioprotective properties.', 'Ghrelin receptor agonist providing strong GH release. Also has direct cardiac protective effects independent of GH.', 200, 300, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth','recovery'], 'Most potent GHRP but causes cortisol/prolactin increase. Desensitizes faster than Ipamorelin.', 'Store at 2-8°C.', '[{"title":"Hexarelin cardioprotective effects","type":"preclinical"}]', 'Research chemical.', true, true, false, false),
('ghrp2', 'GHRP-2', ARRAY['Growth Hormone Releasing Peptide 2','Pralmorelin'], 'gh_secretagogue', 'Potent GH secretagogue with strong appetite-stimulating effects.', 'Ghrelin receptor agonist with potent GH release. Increases appetite via ghrelin pathway activation.', 100, 300, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth','recovery','fat_loss'], 'Strong GH release but increases cortisol and hunger. Pair with CJC-1295 no DAC.', 'Store at 2-8°C. Reconstitute with bacteriostatic water.', '[{"title":"GHRP-2 GH release kinetics","type":"RCT"}]', 'Research chemical.', true, true, false, false),
('ghrp6', 'GHRP-6', ARRAY['Growth Hormone Releasing Peptide 6'], 'gh_secretagogue', 'GH secretagogue known for strong appetite stimulation.', 'Ghrelin mimetic that strongly stimulates GH release and appetite. Increases gastric motility.', 100, 300, 'mcg', 0.5, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth','recovery'], 'Strong hunger effect makes it useful for those needing appetite stimulation. Pair with Mod GRF.', 'Store at 2-8°C.', '[{"title":"GHRP-6 appetite and GH effects","type":"RCT"}]', 'Research chemical.', true, true, false, false),
('igf1_lr3', 'IGF-1 LR3', ARRAY['Long R3 IGF-1','Insulin-like Growth Factor'], 'gh_secretagogue', 'Long-acting IGF-1 analog for muscle growth and recovery.', 'Bypasses IGF-binding proteins for extended IGF-1 receptor activation promoting muscle hypertrophy and repair.', 20, 50, 'mcg', 24, ARRAY['subcutaneous','intramuscular'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth','recovery'], 'Use with caution. Monitor blood glucose. Do not stack with insulin.', 'Store at -20°C lyophilized. 2-8°C reconstituted, use within 30 days.', '[{"title":"IGF-1 LR3 anabolic effects","type":"preclinical"}]', 'Research chemical. High risk peptide.', true, true, false, false),
('follistatin344', 'Follistatin 344', ARRAY['FST-344','Follistatin'], 'hormone', 'Myostatin inhibitor promoting muscle growth.', 'Binds and neutralizes myostatin and activin, removing the brake on muscle growth and promoting hypertrophy.', 100, 100, 'mcg', 3, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['muscle_growth'], 'Use in short cycles only. Monitor liver function.', 'Store at -20°C. Very temperature sensitive.', '[{"title":"Follistatin myostatin inhibition","type":"preclinical"}]', 'Research chemical. Very limited human data.', true, true, false, false),
('mk677', 'MK-677', ARRAY['Ibutamoren','Nutrobal'], 'gh_secretagogue', 'Oral GH secretagogue with 24-hour IGF-1 elevation.', 'Non-peptide ghrelin receptor agonist providing sustained GH and IGF-1 elevation via oral dosing.', 10, 25, 'mg', 24, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['fat_loss','muscle_growth','sleep','recovery'], 'Oral convenience. Increases appetite and water retention. Monitor blood glucose.', 'Store at room temperature. Oral capsule form.', '[{"title":"MK-677 GH and IGF-1 elevation","type":"RCT"}]', 'Research chemical. Not FDA approved.', true, false, false, false)
ON CONFLICT (slug) DO NOTHING;

-- Part 3: Cognitive, Sleep, Immune
INSERT INTO public.peptide_library (slug, name, aliases, category, description, mechanism, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, routes, forms, goals, stacking_notes, storage_notes, research_references, legal_note, wada_caution, clinician_only, pregnancy_safe, lactation_safe) VALUES
('selank', 'Selank', ARRAY['TP-7','Selanc'], 'cognitive', 'Anxiolytic nootropic peptide with immune-modulating properties.', 'Modulates IL-6 and BDNF expression, enhances GABAergic neurotransmission, and stabilizes enkephalin degradation.', 200, 400, 'mcg', 0.3, ARRAY['nasal','subcutaneous'], ARRAY['nasal_spray','lyophilized_vial'], ARRAY['cognition','immune_support'], 'Combines well with Semax for comprehensive cognitive support. Good for HPA axis support.', 'Store at 2-8°C. Nasal spray stable 30 days.', '[{"title":"Selank anxiolytic and immunomodulatory effects","type":"RCT"}]', 'Approved in Russia. Research chemical elsewhere.', false, false, false, false),
('semax', 'Semax', ARRAY['ACTH 4-10 analog','Heptapeptide'], 'cognitive', 'Nootropic peptide enhancing BDNF and cognitive function.', 'Synthetic ACTH 4-10 fragment that increases BDNF, NGF, and enhances attention, memory, and learning.', 200, 600, 'mcg', 0.5, ARRAY['nasal'], ARRAY['nasal_spray'], ARRAY['cognition'], 'Pair with Selank for anxiolytic balance. Can add to any protocol for cognitive support.', 'Store at 2-8°C. Nasal formulation.', '[{"title":"Semax cognitive enhancement","type":"RCT"}]', 'Approved in Russia. Research chemical elsewhere.', false, false, false, false),
('dihexa', 'Dihexa', ARRAY['N-hexanoic-Tyr-Ile-(6)-aminohexanoic amide'], 'cognitive', 'Potent cognitive enhancer with neurotrophin-like activity.', 'Activates hepatocyte growth factor (HGF/MET) receptor system, promoting synaptogenesis and neuronal repair.', 10, 20, 'mg', 6, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['cognition'], 'Extremely potent. Use alone initially. Monitor for headaches.', 'Store at room temperature in sealed container.', '[{"title":"Dihexa cognitive effects via HGF/MET","type":"preclinical"}]', 'Research chemical. Very limited human data.', false, true, false, false),
('pe2228', 'PE-22-28', ARRAY['Spadin analog'], 'cognitive', 'Antidepressant peptide targeting TREK-1 channels.', 'Blocks TREK-1 potassium channels, increasing serotonergic neurotransmission with rapid antidepressant effects.', 50, 100, 'mcg', 1, ARRAY['nasal'], ARRAY['nasal_spray'], ARRAY['cognition'], 'Novel mechanism. Can complement Selank/Semax stack.', 'Store at 2-8°C.', '[{"title":"PE-22-28 antidepressant mechanism","type":"preclinical"}]', 'Research chemical.', false, true, false, false),
('cerebrolysin', 'Cerebrolysin', ARRAY['FPF-1070'], 'cognitive', 'Neurotrophic peptide mixture for neuroprotection and cognitive support.', 'Porcine brain-derived peptide mixture with neurotrophic effects mimicking BDNF and NGF activity.', 1, 10, 'mg', 1, ARRAY['intramuscular'], ARRAY['pre_mixed'], ARRAY['cognition','recovery'], 'Must be injected IM. Prescription product in many countries.', 'Store at 2-8°C. Pre-mixed solution.', '[{"title":"Cerebrolysin neuroprotection","type":"RCT"}]', 'Approved in many countries for neurological conditions.', false, true, false, false),
('dsip', 'DSIP', ARRAY['Delta Sleep-Inducing Peptide'], 'sleep', 'Sleep-promoting nonapeptide that modulates sleep architecture.', 'Modulates sleep spindle activity and promotes delta wave sleep. Acts on multiple neurotransmitter systems.', 100, 250, 'mcg', 0.25, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['sleep'], 'Use pre-bed. Can combine with CJC/Ipa taken pre-bed for synergistic sleep + GH benefits.', 'Store at 2-8°C. Very short half-life.', '[{"title":"DSIP sleep architecture effects","type":"RCT"}]', 'Research chemical.', false, false, false, false),
('thymosin_a1', 'Thymosin Alpha-1', ARRAY['Ta1','Zadaxin'], 'immune', 'Immune modulator enhancing T-cell function and NK cell activity.', 'Enhances T-cell maturation, increases NK cell cytotoxicity, and modulates dendritic cell function for balanced immune response.', 1600, 1600, 'mcg', 2, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['immune_support','longevity'], 'Cornerstone of immune protocols. Pairs with LL-37 for antimicrobial support.', 'Store at 2-8°C. Standard dosing is 1.6mg.', '[{"title":"Thymosin Alpha-1 immune modulation","type":"RCT"}]', 'FDA orphan drug status. Approved in multiple countries.', false, true, false, false),
('ll37', 'LL-37', ARRAY['Cathelicidin','Human Antimicrobial Peptide'], 'antimicrobial', 'Human antimicrobial peptide with broad-spectrum activity against bacteria, viruses, and fungi.', 'Disrupts microbial membranes, modulates immune cell recruitment, and has anti-biofilm properties.', 50, 100, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['immune_support'], 'Pairs with Thymosin Alpha-1 for immune protocols. Use for chronic infections.', 'Store at -20°C lyophilized. 2-8°C reconstituted.', '[{"title":"LL-37 antimicrobial mechanisms","type":"preclinical"}]', 'Research chemical.', false, true, false, false),
('vip', 'VIP', ARRAY['Vasoactive Intestinal Peptide'], 'immune', 'Neuropeptide with anti-inflammatory and immune regulatory functions.', 'Regulates innate and adaptive immunity, reduces inflammatory cytokines, supports mucosal immunity and circadian rhythm.', 50, 50, 'mcg', 0.5, ARRAY['nasal'], ARRAY['nasal_spray'], ARRAY['immune_support'], 'Key peptide for mold illness (CIRS) protocols. Use nasal route.', 'Store at 2-8°C. Nasal formulation.', '[{"title":"VIP anti-inflammatory effects","type":"RCT"}]', 'Research chemical. Used off-label for CIRS.', false, true, false, false)
ON CONFLICT (slug) DO NOTHING;

-- Part 4: Weight Management, Sexual Health, Longevity
INSERT INTO public.peptide_library (slug, name, aliases, category, description, mechanism, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, routes, forms, goals, stacking_notes, storage_notes, research_references, legal_note, wada_caution, clinician_only, pregnancy_safe, lactation_safe) VALUES
('semaglutide', 'Semaglutide', ARRAY['Ozempic','Wegovy','GLP-1 agonist'], 'weight_management', 'GLP-1 receptor agonist for weight loss and blood sugar control.', 'GLP-1 receptor agonist that enhances insulin secretion, suppresses glucagon, delays gastric emptying, and reduces appetite centrally.', 250, 2400, 'mcg', 168, ARRAY['subcutaneous'], ARRAY['pre_mixed'], ARRAY['fat_loss','metabolic_health'], 'Do NOT combine with other GLP-1 agonists. Can use with GH secretagogues.', 'Store at 2-8°C. In-use pen stable 56 days.', '[{"title":"Semaglutide STEP trials","type":"RCT"}]', 'FDA approved (Ozempic/Wegovy).', false, true, false, false),
('tirzepatide', 'Tirzepatide', ARRAY['Mounjaro','Zepbound'], 'weight_management', 'Dual GIP/GLP-1 receptor agonist for superior weight loss.', 'Dual incretin agonist targeting both GIP and GLP-1 receptors for enhanced glucose control and weight loss.', 2500, 15000, 'mcg', 120, ARRAY['subcutaneous'], ARRAY['pre_mixed'], ARRAY['fat_loss','metabolic_health'], 'Do NOT combine with GLP-1 agonists. Most potent weight loss peptide.', 'Store at 2-8°C.', '[{"title":"Tirzepatide SURMOUNT trials","type":"RCT"}]', 'FDA approved (Mounjaro/Zepbound).', false, true, false, false),
('retatrutide', 'Retatrutide', ARRAY['LY3437943','Triple G'], 'weight_management', 'Triple agonist targeting GLP-1, GIP, and glucagon receptors.', 'Triple incretin agonist providing weight loss via appetite suppression, increased energy expenditure, and metabolic optimization.', 1000, 12000, 'mcg', 144, ARRAY['subcutaneous'], ARRAY['pre_mixed'], ARRAY['fat_loss','metabolic_health'], 'Do NOT combine with other incretin agonists.', 'Store at 2-8°C.', '[{"title":"Retatrutide phase 2 trials","type":"RCT"}]', 'Investigational. Phase 3 trials ongoing.', false, true, false, false),
('survodutide', 'Survodutide', ARRAY['BI 456906'], 'weight_management', 'Dual GLP-1/glucagon receptor agonist.', 'Activates both GLP-1 and glucagon receptors for weight loss plus hepatic fat reduction.', 500, 4800, 'mcg', 120, ARRAY['subcutaneous'], ARRAY['pre_mixed'], ARRAY['fat_loss','metabolic_health'], 'Do NOT combine with GLP-1 agonists.', 'Store at 2-8°C.', '[{"title":"Survodutide obesity trials","type":"RCT"}]', 'Investigational.', false, true, false, false),
('liraglutide', 'Liraglutide', ARRAY['Saxenda','Victoza'], 'weight_management', 'GLP-1 receptor agonist for weight management.', 'GLP-1 analog with daily dosing for appetite suppression and blood sugar control.', 600, 3000, 'mcg', 13, ARRAY['subcutaneous'], ARRAY['pre_mixed'], ARRAY['fat_loss','metabolic_health'], 'Daily injection. Can transition to weekly semaglutide.', 'Store at 2-8°C.', '[{"title":"Liraglutide SCALE trials","type":"RCT"}]', 'FDA approved (Saxenda/Victoza).', false, true, false, false),
('aod9604', 'AOD-9604', ARRAY['Anti-Obesity Drug 9604','HGH Fragment'], 'weight_management', 'Modified GH fragment targeting fat metabolism without GH side effects.', 'Modified amino acids 176-191 of growth hormone that stimulates lipolysis without affecting blood sugar or growth.', 250, 500, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss'], 'Can combine with GH secretagogues. No IGF-1 increase.', 'Store at 2-8°C.', '[{"title":"AOD-9604 fat metabolism","type":"RCT"}]', 'TGA approved in Australia as food supplement.', false, false, false, false),
('frag176_191', 'Fragment 176-191', ARRAY['HGH Frag','GH Fragment'], 'weight_management', 'GH fragment peptide for targeted fat loss.', 'C-terminal fragment of GH that promotes lipolysis and fat oxidation without anabolic or diabetogenic effects.', 250, 500, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss'], 'Similar to AOD-9604 but unmodified fragment. Take on empty stomach.', 'Store at 2-8°C.', '[{"title":"HGH Fragment 176-191 lipolysis","type":"preclinical"}]', 'Research chemical.', false, false, false, false),
('pt141', 'PT-141', ARRAY['Bremelanotide','Vyleesi'], 'sexual_health', 'Melanocortin receptor agonist for sexual dysfunction.', 'MC3R/MC4R agonist acting centrally on sexual arousal pathways in the hypothalamus.', 1000, 2000, 'mcg', 2.7, ARRAY['subcutaneous','nasal'], ARRAY['lyophilized_vial','nasal_spray'], ARRAY['libido'], 'Use 45 min before activity. Max 8 doses/month. Monitor blood pressure.', 'Store at 2-8°C. Protect from light.', '[{"title":"Bremelanotide HSDD trials","type":"RCT"}]', 'FDA approved (Vyleesi) for HSDD in premenopausal women.', false, true, false, false),
('melanotan2', 'Melanotan II', ARRAY['MT-2','MT-II'], 'skin', 'Melanocortin agonist for tanning and libido enhancement.', 'Non-selective melanocortin receptor agonist promoting melanogenesis and sexual arousal.', 250, 500, 'mcg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['skin_health','libido'], 'Start low to assess tolerance. Causes nausea initially.', 'Store at 2-8°C. Protect from light.', '[{"title":"Melanotan II melanogenesis","type":"RCT"}]', 'Research chemical. Banned in some countries.', true, false, false, false),
('kisspeptin', 'Kisspeptin', ARRAY['Kisspeptin-10','KISS1'], 'hormone', 'Hypothalamic hormone regulating reproductive function.', 'Stimulates GnRH neurons to trigger LH and FSH release, key regulator of puberty and reproductive function.', 50, 100, 'mcg', 0.5, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['libido','metabolic_health'], 'Use for natural hormone optimization. Can support PCT protocols.', 'Store at -20°C lyophilized.', '[{"title":"Kisspeptin reproductive endocrinology","type":"RCT"}]', 'Research chemical.', false, true, false, false),
('gonadorelin', 'Gonadorelin', ARRAY['GnRH','Factrel','Lutrepulse'], 'hormone', 'Synthetic GnRH for gonadotropin stimulation.', 'Stimulates pituitary release of LH and FSH to support natural testosterone and fertility.', 50, 100, 'mcg', 0.1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['libido','metabolic_health'], 'Used in TRT protocols to maintain fertility. Pair with HCG alternative.', 'Store at 2-8°C.', '[{"title":"GnRH pulsatile therapy","type":"RCT"}]', 'FDA approved for diagnostic and therapeutic use.', false, true, false, false),
('oxytocin', 'Oxytocin', ARRAY['Pitocin','OXT'], 'hormone', 'Neuropeptide involved in bonding, stress reduction, and social behavior.', 'Modulates social bonding, reduces cortisol, enhances trust and empathy via hypothalamic-limbic pathways.', 10, 20, 'IU', 0.1, ARRAY['nasal'], ARRAY['nasal_spray'], ARRAY['cognition','sleep'], 'Use nasal route for CNS effects. Low doses for anxiolytic effect.', 'Store at 2-8°C.', '[{"title":"Oxytocin social behavior effects","type":"RCT"}]', 'FDA approved (Pitocin) for obstetric use. Off-label for behavioral.', false, true, false, false)
ON CONFLICT (slug) DO NOTHING;

-- Part 5: Longevity, Mitochondrial, Bioregulators, Skin
INSERT INTO public.peptide_library (slug, name, aliases, category, description, mechanism, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, routes, forms, goals, stacking_notes, storage_notes, research_references, legal_note, wada_caution, clinician_only, pregnancy_safe, lactation_safe) VALUES
('epithalon', 'Epithalon', ARRAY['Epitalon','Epithalone'], 'longevity', 'Telomerase-activating peptide for anti-aging.', 'Activates telomerase to lengthen telomeres, regulates melatonin production, and has anti-aging effects on neuroendocrine system.', 5000, 10000, 'mcg', 2, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['longevity','sleep'], 'Run in 10-20 day cycles. Can combine with other longevity peptides.', 'Store at 2-8°C.', '[{"title":"Epithalon telomerase activation","type":"RCT"}]', 'Research chemical.', false, false, false, false),
('mots_c', 'MOTS-c', ARRAY['Mitochondrial ORF of Twelve S','MOTS'], 'mitochondrial', 'Mitochondrial-derived peptide enhancing metabolic function.', 'Activates AMPK pathway, enhances glucose uptake, improves mitochondrial function and exercise capacity.', 5000, 10000, 'mcg', 4, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['fat_loss','longevity','metabolic_health'], 'Pairs well with SS-31 for mitochondrial support. Good with exercise.', 'Store at -20°C lyophilized. 2-8°C reconstituted.', '[{"title":"MOTS-c metabolic regulation","type":"preclinical"}]', 'Research chemical.', false, false, false, false),
('humanin', 'Humanin', ARRAY['HN','Humanin Peptide'], 'mitochondrial', 'Mitochondrial-derived peptide with neuroprotective and cytoprotective properties.', 'Mitochondrial peptide that protects against apoptosis, reduces oxidative stress, and has insulin-sensitizing effects.', 1000, 3000, 'mcg', 3, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['longevity','cognition','metabolic_health'], 'Complements MOTS-c for comprehensive mitochondrial support.', 'Store at -20°C lyophilized.', '[{"title":"Humanin cytoprotection","type":"preclinical"}]', 'Research chemical.', false, false, false, false),
('ss31', 'SS-31', ARRAY['Elamipretide','Bendavia','MTP-131'], 'mitochondrial', 'Mitochondria-targeted peptide reducing oxidative damage.', 'Concentrates in inner mitochondrial membrane, stabilizes cardiolipin, reduces ROS production, and restores bioenergetics.', 5000, 40000, 'mcg', 4, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['longevity','recovery','metabolic_health'], 'Key mitochondrial peptide. Pairs with MOTS-c and NAD+.', 'Store at -20°C. Temperature sensitive.', '[{"title":"Elamipretide mitochondrial function","type":"RCT"}]', 'Investigational. In clinical trials for mitochondrial diseases.', false, false, false, false),
('nad_plus', 'NAD+', ARRAY['Nicotinamide Adenine Dinucleotide','NAD'], 'longevity', 'Essential coenzyme for cellular energy and DNA repair.', 'Critical cofactor for sirtuins, PARPs, and CD38. Declines with age. Supplementation restores cellular energy metabolism.', 100, 500, 'mg', 1, ARRAY['subcutaneous'], ARRAY['lyophilized_vial'], ARRAY['longevity','cognition','metabolic_health'], 'Foundational longevity molecule. Combines with everything.', 'Store at 2-8°C. Protect from light.', '[{"title":"NAD+ aging and metabolism","type":"RCT"}]', 'Supplement. Injectable form is compounded.', false, false, false, false),
('cortagen', 'Cortagen', ARRAY['Cortex Bioregulator'], 'bioregulator', 'Khavinson bioregulator peptide for brain cortex support.', 'Short peptide bioregulator targeting cerebral cortex gene expression for neuroprotection and cognitive maintenance.', 10, 20, 'mcg', 2, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['cognition','longevity'], 'Part of Khavinson bioregulator system. Can combine with Pinealon.', 'Store at room temperature.', '[{"title":"Cortagen bioregulator effects","type":"preclinical"}]', 'Dietary supplement in Russia.', false, false, false, false),
('pinealon', 'Pinealon', ARRAY['Pineal Bioregulator','EDR'], 'bioregulator', 'Bioregulator peptide supporting pineal gland function.', 'Tripeptide (Glu-Asp-Arg) targeting pineal gland gene expression, supporting melatonin production and circadian rhythm.', 10, 20, 'mcg', 2, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['sleep','longevity'], 'Supports natural melatonin production. Combine with Epithalon.', 'Store at room temperature.', '[{"title":"Pinealon pineal function","type":"preclinical"}]', 'Dietary supplement in Russia.', false, false, false, false),
('vilon', 'Vilon', ARRAY['Thymus Bioregulator','KE'], 'bioregulator', 'Bioregulator dipeptide supporting thymus function and immunity.', 'Dipeptide (Lys-Glu) that regulates thymus gene expression, supporting T-cell maturation and immune function.', 10, 20, 'mcg', 1, ARRAY['oral'], ARRAY['oral_capsule'], ARRAY['immune_support','longevity'], 'Pairs with Thymosin Alpha-1 for immune support.', 'Store at room temperature.', '[{"title":"Vilon immunomodulation","type":"preclinical"}]', 'Dietary supplement in Russia.', false, false, false, false),
('matrixyl', 'Matrixyl', ARRAY['Palmitoyl Pentapeptide-4','Pal-KTTKS'], 'skin', 'Collagen-stimulating peptide for topical anti-aging.', 'Stimulates collagen I, III, and IV synthesis in fibroblasts. Reduces wrinkle depth and improves skin texture.', 0, 0, 'mg', 0, ARRAY['topical'], ARRAY['cream'], ARRAY['skin_health'], 'Combine with GHK-Cu for comprehensive skin protocol.', 'Stable at room temperature in formulation.', '[{"title":"Matrixyl collagen synthesis","type":"RCT"}]', 'Cosmetic ingredient. Widely available.', false, false, true, true),
('argireline', 'Argireline', ARRAY['Acetyl Hexapeptide-3'], 'skin', 'Topical peptide reducing expression wrinkles.', 'Inhibits SNARE complex formation at neuromuscular junction, reducing muscle contraction depth similar to topical botox.', 0, 0, 'mg', 0, ARRAY['topical'], ARRAY['cream'], ARRAY['skin_health'], 'Combine with Snap-8 for enhanced effect.', 'Stable at room temperature in formulation.', '[{"title":"Argireline wrinkle reduction","type":"RCT"}]', 'Cosmetic ingredient.', false, false, true, true),
('snap8', 'Snap-8', ARRAY['Acetyl Octapeptide-3'], 'skin', 'Enhanced wrinkle-reducing peptide.', 'More potent SNARE complex inhibitor than Argireline with deeper wrinkle reduction.', 0, 0, 'mg', 0, ARRAY['topical'], ARRAY['cream'], ARRAY['skin_health'], 'Use with Argireline for synergistic wrinkle reduction.', 'Stable at room temperature.', '[{"title":"Snap-8 anti-wrinkle efficacy","type":"RCT"}]', 'Cosmetic ingredient.', false, false, true, true),
('leuphasyl', 'Leuphasyl', ARRAY['Pentapeptide-18'], 'skin', 'Enkephalin-mimetic peptide for expression line reduction.', 'Mimics enkephalin to reduce catecholamine release at neuromuscular junction, complementing Argireline mechanism.', 0, 0, 'mg', 0, ARRAY['topical'], ARRAY['cream'], ARRAY['skin_health'], 'Synergistic with Argireline via different mechanism.', 'Stable at room temperature.', '[{"title":"Leuphasyl anti-aging","type":"preclinical"}]', 'Cosmetic ingredient.', false, false, true, true)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- PEPTIDE INTERACTIONS (safety rules)
-- ============================================================
INSERT INTO public.peptide_interactions (peptide_a_slug, peptide_b_slug, interaction_type, severity, description, recommendation) VALUES
('cjc1295_no_dac', 'ipamorelin', 'synergistic', 'info', 'Gold standard GH secretagogue combination. CJC-1295 extends GH release while Ipamorelin provides clean pulsatile release.', 'Inject together subcutaneously pre-bed on empty stomach.'),
('bpc157', 'tb500', 'synergistic', 'info', 'Complementary healing mechanisms. BPC-157 promotes angiogenesis while TB-500 enhances cell migration.', 'Can be injected together or staggered by 30 minutes. Inject near injury site.'),
('cjc1295_dac', 'cjc1295_no_dac', 'antagonistic', 'warning', 'Both are GHRH analogs competing for the same receptor. Combining provides no benefit and may cause desensitization.', 'Choose one GHRH analog only. Do not combine.'),
('semaglutide', 'tirzepatide', 'contraindicated', 'critical', 'Both target GLP-1 receptors. Combining causes dangerous hypoglycemia and severe GI side effects.', 'NEVER combine. Choose one GLP-1 agonist only.'),
('semaglutide', 'liraglutide', 'contraindicated', 'critical', 'Both are GLP-1 receptor agonists. Combining doubles the risk of pancreatitis and severe hypoglycemia.', 'NEVER combine. Switch from one to the other with washout period.'),
('tirzepatide', 'retatrutide', 'contraindicated', 'critical', 'Both target incretin receptors. Dangerous overlap in GLP-1 agonism.', 'NEVER combine. Choose one incretin-based therapy.'),
('semaglutide', 'retatrutide', 'contraindicated', 'critical', 'Overlapping GLP-1 agonism creates dangerous hypoglycemia risk.', 'NEVER combine incretin therapies.'),
('cjc1295_dac', 'hexarelin', 'caution', 'warning', 'Hexarelin causes cortisol and prolactin elevation. Combined with sustained GH from CJC-DAC, this may cause significant side effects.', 'Prefer Ipamorelin over Hexarelin when combining with CJC-1295 DAC.'),
('ghrp6', 'ghrp2', 'caution', 'caution', 'Both are GHRPs competing for ghrelin receptor. No benefit to combining and increases side effects.', 'Choose one GHRP. GHRP-2 is preferred for less hunger stimulation.'),
('cjc1295_no_dac', 'sermorelin', 'antagonistic', 'caution', 'Both are GHRH analogs. No synergy from combining two GHRH-pathway peptides.', 'Use one GHRH analog. Pair with a GHRP instead.'),
('igf1_lr3', 'mk677', 'caution', 'warning', 'Both increase IGF-1 significantly. Combined use risks supraphysiological IGF-1 levels.', 'Monitor IGF-1 levels closely. Consider using only one at a time.'),
('igf1_lr3', 'cjc1295_dac', 'caution', 'warning', 'Exogenous IGF-1 plus GH secretagogue may cause IGF-1 overshoot and insulin resistance.', 'Monitor IGF-1 and fasting glucose. Reduce doses if combining.'),
('bpc157', 'ghk_cu', 'synergistic', 'info', 'Complementary healing: BPC-157 for deep tissue repair, GHK-Cu for collagen synthesis and skin.', 'Excellent combination for injury recovery with skin/scar healing.'),
('thymosin_a1', 'll37', 'synergistic', 'info', 'Complementary immune support: Ta1 for adaptive immunity, LL-37 for innate antimicrobial defense.', 'Standard immune protocol combination. Safe to use together.'),
('selank', 'semax', 'synergistic', 'info', 'Complementary nootropics: Selank for anxiety reduction, Semax for cognitive enhancement and focus.', 'Can be used together nasally. Selank morning, Semax as needed.'),
('mots_c', 'ss31', 'synergistic', 'info', 'Both target mitochondrial function via different mechanisms. MOTS-c activates AMPK, SS-31 stabilizes cardiolipin.', 'Excellent mitochondrial support stack.'),
('epithalon', 'pinealon', 'synergistic', 'info', 'Both support pineal/melatonin function. Epithalon activates telomerase, Pinealon supports pineal gene expression.', 'Good longevity combination.'),
('hexarelin', 'ghrp2', 'caution', 'caution', 'Both are GHRPs with significant cortisol/prolactin elevation. Combining amplifies side effects.', 'Do not combine. Use one GHRP only.'),
('pt141', 'melanotan2', 'caution', 'caution', 'Both are melanocortin agonists. Overlapping receptor activity with additive side effects (nausea, BP changes).', 'Do not combine. Choose one melanocortin peptide.'),
('mk677', 'semaglutide', 'caution', 'caution', 'MK-677 increases appetite and blood sugar. Semaglutide suppresses appetite. Opposing effects reduce efficacy of both.', 'Generally not recommended together. If combining, monitor blood glucose closely.'),
('follistatin344', 'igf1_lr3', 'caution', 'warning', 'Both promote significant muscle growth. Combined use increases risk of uncontrolled tissue growth.', 'Use separately. Monitor closely if combining.'),
('bpc157', 'kpv', 'synergistic', 'info', 'Complementary gut healing: BPC-157 for mucosal repair, KPV for NF-kB-mediated inflammation reduction.', 'Excellent gut healing stack. Can take both orally.'),
('dsip', 'ipamorelin', 'synergistic', 'info', 'DSIP enhances deep sleep, Ipamorelin promotes GH release during sleep. Complementary pre-bed stack.', 'Take both pre-bed for synergistic sleep and GH optimization.'),
('nad_plus', 'epithalon', 'synergistic', 'info', 'NAD+ supports sirtuin activity while Epithalon activates telomerase. Complementary anti-aging mechanisms.', 'Foundational longevity combination.'),
('humanin', 'mots_c', 'synergistic', 'info', 'Both are mitochondrial-derived peptides with complementary cytoprotective and metabolic effects.', 'Comprehensive mitochondrial support when used together.')
ON CONFLICT DO NOTHING;

-- ============================================================
-- PEPTIDE CONTRAINDICATIONS
-- ============================================================
INSERT INTO public.peptide_contraindications (peptide_slug, condition, severity, description, recommendation) VALUES
('bpc157', 'Active cancer', 'critical', 'BPC-157 promotes angiogenesis which may support tumor blood vessel growth.', 'Contraindicated. Do not use with active malignancy or history of cancer within 5 years.'),
('bpc157', 'Pregnancy', 'critical', 'No safety data in pregnancy. Angiogenic effects pose theoretical risk.', 'Do not use during pregnancy.'),
('tb500', 'Active cancer', 'critical', 'TB-500 promotes cell migration and angiogenesis which may promote tumor spread.', 'Contraindicated with any active malignancy.'),
('tb500', 'Recent heart attack', 'warning', 'May affect cardiac remodeling post-MI. Limited safety data.', 'Wait at least 6 months post-MI. Use only under medical supervision.'),
('cjc1295_dac', 'Active cancer', 'critical', 'GH/IGF-1 elevation may promote tumor growth.', 'Contraindicated. All GH secretagogues should be avoided with active cancer.'),
('cjc1295_dac', 'Diabetic retinopathy', 'critical', 'IGF-1 elevation can worsen diabetic retinopathy.', 'Contraindicated with active retinopathy.'),
('cjc1295_dac', 'Uncontrolled diabetes', 'warning', 'GH elevation can worsen insulin resistance and blood sugar control.', 'Control diabetes first. Monitor glucose closely if used.'),
('ipamorelin', 'Active cancer', 'critical', 'GH/IGF-1 elevation may promote tumor growth.', 'Contraindicated with active cancer.'),
('sermorelin', 'Active cancer', 'critical', 'GH secretagogue that may promote tumor growth via IGF-1.', 'Contraindicated with active cancer.'),
('tesamorelin', 'Active cancer', 'critical', 'GH secretagogue contraindicated with malignancy.', 'Contraindicated per FDA label.'),
('hexarelin', 'Active cancer', 'critical', 'GH secretagogue with cancer risk.', 'Contraindicated with active cancer.'),
('ghrp2', 'Active cancer', 'critical', 'GH secretagogue with cancer risk.', 'Contraindicated with active cancer.'),
('ghrp6', 'Active cancer', 'critical', 'GH secretagogue with cancer risk.', 'Contraindicated with active cancer.'),
('igf1_lr3', 'Active cancer', 'critical', 'Direct IGF-1 receptor activation strongly promotes tumor growth.', 'Absolutely contraindicated. Highest cancer risk of all peptides.'),
('igf1_lr3', 'Diabetes', 'warning', 'Can cause severe hypoglycemia. Acts similarly to insulin.', 'Monitor blood glucose very carefully. Start at lowest dose.'),
('mk677', 'Active cancer', 'critical', 'Sustained IGF-1 elevation promotes tumor growth.', 'Contraindicated with active or recent cancer.'),
('mk677', 'Diabetes', 'warning', 'MK-677 raises fasting glucose and can worsen insulin resistance.', 'Monitor glucose closely. May need to reduce dose or discontinue.'),
('pt141', 'Uncontrolled hypertension', 'critical', 'PT-141 can cause acute blood pressure elevation.', 'Control blood pressure before use. Contraindicated if uncontrolled.'),
('pt141', 'Cardiovascular disease', 'warning', 'Risk of blood pressure spikes with underlying cardiovascular disease.', 'Use with caution. Monitor blood pressure before and after dosing.'),
('pt141', 'Pregnancy', 'critical', 'No safety data. Melanocortin agonism may affect fetal development.', 'Contraindicated in pregnancy.'),
('semaglutide', 'Medullary thyroid cancer', 'critical', 'GLP-1 agonists carry boxed warning for MTC risk based on rodent studies.', 'Contraindicated with personal or family history of MTC or MEN2.'),
('semaglutide', 'Pancreatitis history', 'warning', 'GLP-1 agonists increase pancreatitis risk.', 'Use with caution. Monitor for abdominal symptoms.'),
('tirzepatide', 'Medullary thyroid cancer', 'critical', 'Incretin agonist with MTC boxed warning.', 'Contraindicated with personal/family history of MTC or MEN2.'),
('tirzepatide', 'Pancreatitis history', 'warning', 'Increased pancreatitis risk with incretin therapies.', 'Monitor closely. Discontinue if pancreatitis develops.'),
('melanotan2', 'Melanoma history', 'critical', 'Melanocortin agonism may promote melanoma growth or recurrence.', 'Contraindicated with any history of melanoma.'),
('melanotan2', 'Multiple dysplastic nevi', 'warning', 'May increase melanoma risk in predisposed individuals.', 'Dermatological evaluation required before use.'),
('follistatin344', 'Liver disease', 'warning', 'May affect liver function and requires hepatic monitoring.', 'Monitor liver enzymes. Avoid in active liver disease.'),
('ll37', 'Autoimmune disease', 'caution', 'LL-37 can modulate immune response unpredictably in autoimmune conditions.', 'Use with caution under medical supervision.'),
('thymosin_a1', 'Organ transplant', 'warning', 'Immune enhancement may trigger transplant rejection.', 'Contraindicated in transplant recipients on immunosuppression.'),
('cerebrolysin', 'Epilepsy', 'warning', 'Neurotrophic effects may lower seizure threshold.', 'Use with caution. Monitor for seizure activity.'),
('dihexa', 'Cancer history', 'caution', 'HGF/MET pathway activation has been linked to tumor progression.', 'Use with caution. Limited safety data available.')
ON CONFLICT DO NOTHING;

-- ============================================================
-- PEPTIDE LAB THRESHOLDS
-- ============================================================
INSERT INTO public.peptide_lab_thresholds (peptide_slug, biomarker_name, threshold_value, direction, severity, message, recommendation) VALUES
('cjc1295_dac', 'IGF-1', 300, 'above', 'warning', 'IGF-1 already elevated. GH secretagogue may push levels supraphysiological.', 'Reduce dose or skip GH secretagogue until IGF-1 normalizes. Recheck in 4 weeks.'),
('cjc1295_no_dac', 'IGF-1', 300, 'above', 'warning', 'IGF-1 already elevated at {value} ng/mL.', 'Reduce dose or hold GH secretagogue. Recheck IGF-1 in 4 weeks.'),
('ipamorelin', 'IGF-1', 300, 'above', 'warning', 'IGF-1 elevated. Adding Ipamorelin may cause supraphysiological IGF-1.', 'Consider lower dose. Monitor IGF-1 every 4-6 weeks.'),
('sermorelin', 'IGF-1', 300, 'above', 'caution', 'IGF-1 already near upper limit.', 'Monitor IGF-1. Consider lower starting dose.'),
('mk677', 'IGF-1', 300, 'above', 'warning', 'MK-677 provides sustained IGF-1 elevation. Already elevated baseline increases risk.', 'Avoid MK-677 or use minimal dose with frequent monitoring.'),
('mk677', 'Fasting Glucose', 126, 'above', 'warning', 'Fasting glucose in diabetic range. MK-677 worsens insulin resistance.', 'MK-677 not recommended. Address glucose control first.'),
('mk677', 'HbA1c', 6.5, 'above', 'warning', 'HbA1c indicates diabetes. MK-677 will worsen glucose control.', 'Contraindicated. Optimize blood sugar before considering GH peptides.'),
('cjc1295_dac', 'Fasting Glucose', 126, 'above', 'caution', 'Elevated fasting glucose. GH secretagogues can worsen insulin resistance.', 'Monitor glucose closely. Consider lower dose or alternative.'),
('igf1_lr3', 'Fasting Glucose', 100, 'above', 'warning', 'IGF-1 LR3 has insulin-like effects. Elevated glucose increases hypoglycemia risk.', 'Extreme caution. Monitor glucose before and after each dose.'),
('igf1_lr3', 'IGF-1', 250, 'above', 'warning', 'IGF-1 already elevated. Exogenous IGF-1 LR3 will push to dangerous levels.', 'Do not use. IGF-1 levels already sufficient.'),
('bpc157', 'CRP', 10, 'above', 'info', 'Highly elevated CRP suggests significant inflammation. BPC-157 may help but investigate root cause.', 'Consider higher end of dose range. Investigate inflammatory source.'),
('bpc157', 'ALT', 65, 'above', 'caution', 'Elevated liver enzymes. Monitor hepatic function during BPC-157 use.', 'Check liver panel in 4 weeks. Consider adding liver support (NAC).'),
('tb500', 'ALT', 65, 'above', 'caution', 'Elevated liver enzymes. Monitor hepatic function during TB-500 use.', 'Monitor liver enzymes every 4 weeks.'),
('follistatin344', 'ALT', 50, 'above', 'warning', 'Follistatin requires healthy liver function. Elevated ALT is concerning.', 'Do not start until liver enzymes normalize. Add liver support.'),
('semaglutide', 'Lipase', 180, 'above', 'warning', 'Elevated lipase increases pancreatitis risk with GLP-1 agonists.', 'Investigate elevated lipase before starting. Consider alternative.'),
('tirzepatide', 'Lipase', 180, 'above', 'warning', 'Elevated lipase. Incretin therapy increases pancreatitis risk.', 'Do not start until lipase normalizes. Rule out pancreatitis.'),
('pt141', 'Blood Pressure Systolic', 140, 'above', 'warning', 'Elevated blood pressure. PT-141 can cause acute BP spikes.', 'Control blood pressure before using PT-141.'),
('thymosin_a1', 'WBC', 2.0, 'below', 'caution', 'Low WBC. Thymosin Alpha-1 immune stimulation may be especially beneficial but requires monitoring.', 'Start at standard dose. Monitor WBC response in 4 weeks.'),
('ll37', 'ANA', 1, 'above', 'caution', 'Positive ANA suggests autoimmune tendency. LL-37 may modulate immune response unpredictably.', 'Use with caution. Monitor autoimmune markers.'),
('semaglutide', 'eGFR', 30, 'below', 'warning', 'Severe renal impairment. GLP-1 agonist dose adjustment required.', 'Reduce dose. Monitor renal function closely.'),
('semaglutide', 'TSH', 0.1, 'below', 'caution', 'Suppressed TSH. GLP-1 agonists carry thyroid C-cell risk.', 'Evaluate thyroid function before starting.')
ON CONFLICT DO NOTHING;

-- ============================================================
-- LAB-TO-PEPTIDE MAPPINGS (Functional Medicine Intelligence)
-- ============================================================
INSERT INTO public.lab_peptide_mappings (lab_type, finding_pattern, finding_description, recommended_peptide_slugs, priority_level, reasoning, prerequisite_note) VALUES
('blood_panel', 'CRP > 3', 'Elevated C-reactive protein indicating systemic inflammation', ARRAY['bpc157','kpv','thymosin_a1'], 3, 'Elevated CRP indicates systemic inflammation. BPC-157 and KPV have anti-inflammatory properties. Thymosin Alpha-1 modulates immune response.', 'Rule out acute infection before starting anti-inflammatory peptide protocol.'),
('blood_panel', 'IGF-1 < 120', 'Low IGF-1 suggesting GH deficiency', ARRAY['cjc1295_no_dac','ipamorelin','sermorelin'], 4, 'Low IGF-1 may indicate GH deficiency. GH secretagogues can restore physiological GH pulsatility.', 'Rule out pituitary pathology. Get baseline GH stimulation test if indicated.'),
('blood_panel', 'ALT > 50 or AST > 50', 'Elevated liver enzymes', ARRAY['bpc157','nad_plus'], 2, 'BPC-157 has hepatoprotective properties. NAD+ supports liver detox pathways. Address root cause first.', 'Identify cause of liver enzyme elevation before starting peptides.'),
('blood_panel', 'Ferritin < 30', 'Low ferritin suggesting iron deficiency', ARRAY['bpc157_oral'], 2, 'BPC-157 oral supports gut mucosal health which can improve iron absorption. Address underlying cause of iron loss.', 'Check for GI bleeding or malabsorption. Supplement iron directly.'),
('blood_panel', 'Fasting Glucose > 100', 'Impaired fasting glucose', ARRAY['mots_c','semaglutide','aod9604'], 3, 'MOTS-c improves glucose uptake via AMPK. Semaglutide improves insulin sensitivity. AOD-9604 supports fat loss without glucose effects.', 'Lifestyle interventions (diet, exercise) should be primary. Peptides are adjunctive.'),
('dutch', 'Low cortisol output', 'DUTCH testing showing low free cortisol and metabolized cortisol', ARRAY['selank','semax'], 3, 'Low cortisol pattern suggests HPA axis dysregulation. Selank supports HPA axis recovery. Semax enhances ACTH fragment activity for adrenal support.', 'Address sleep, stress, and lifestyle factors. Consider adaptogenic herbs alongside.'),
('dutch', 'High cortisol metabolites', 'Elevated cortisol production with high metabolized cortisol', ARRAY['selank','dsip','pinealon'], 2, 'High cortisol production needs calming interventions. Selank reduces anxiety. DSIP normalizes sleep-wake cortisol rhythm. Pinealon supports melatonin.', 'Prioritize stress reduction. Consider circadian rhythm optimization.'),
('dutch', 'Low melatonin metabolites', 'Low 6-OH melatonin sulfate on DUTCH suggesting poor melatonin production', ARRAY['pinealon','epithalon','dsip'], 3, 'Pinealon supports pineal gene expression. Epithalon enhances melatonin synthesis. DSIP promotes delta sleep.', 'Address light exposure, screen time, and sleep hygiene first.'),
('gi_map', 'Elevated zonulin', 'High zonulin indicating intestinal permeability (leaky gut)', ARRAY['bpc157','bpc157_oral','kpv'], 4, 'BPC-157 is the gold standard for gut mucosal healing. Oral BPC targets GI directly. KPV reduces gut inflammation via NF-kB.', 'Address dietary triggers. Remove inflammatory foods first.'),
('gi_map', 'Gut dysbiosis pattern', 'Imbalanced commensal bacteria with opportunistic overgrowth', ARRAY['bpc157_oral','kpv','ll37'], 3, 'BPC-157 oral supports mucosal integrity. KPV reduces inflammatory response. LL-37 has antimicrobial properties for pathogenic overgrowth.', 'Address dysbiosis with diet, probiotics, and antimicrobials first. Peptides support healing.'),
('gi_map', 'H. pylori positive', 'Active Helicobacter pylori infection detected', ARRAY['bpc157','bpc157_oral'], 2, 'BPC-157 has shown anti-H. pylori effects in preclinical studies and supports gastric mucosal healing.', 'Treat H. pylori with standard triple/quad therapy first. BPC-157 supports healing after treatment.'),
('oat', 'Mitochondrial dysfunction markers', 'Elevated succinic, fumaric, or malic acid suggesting mitochondrial impairment', ARRAY['mots_c','ss31','humanin','nad_plus'], 5, 'MOTS-c activates AMPK for mitochondrial biogenesis. SS-31 stabilizes cardiolipin. Humanin is cytoprotective. NAD+ is essential cofactor.', 'Address CoQ10, B vitamins, and magnesium first. Remove mitochondrial toxins.'),
('oat', 'Neurotransmitter imbalance', 'Abnormal HVA/VMA ratio or quinolinic acid elevation', ARRAY['selank','semax','pe2228'], 3, 'Selank modulates GABA and enkephalins. Semax enhances BDNF. PE-22-28 modulates serotonin via TREK-1 channels.', 'Consider neurotransmitter precursors (5-HTP, tyrosine) alongside.'),
('mycotoxin', 'Mold exposure detected', 'Elevated ochratoxin A, aflatoxin, or trichothecene metabolites', ARRAY['nad_plus','bpc157'], 2, 'NAD+ supports Phase II liver detox. BPC-157 supports tissue healing during detox. However, detoxification must be prioritized.', 'CRITICAL: Complete mold avoidance and binder protocol BEFORE aggressive peptide stacking. Many peptides are less effective during active mold exposure.'),
('mycotoxin', 'Elevated gliotoxin', 'Aspergillus-derived gliotoxin indicating active mold colonization', ARRAY['thymosin_a1','ll37','nad_plus'], 3, 'Thymosin Alpha-1 enhances immune response against fungi. LL-37 has antifungal properties. NAD+ supports detox pathways.', 'Treat mold colonization with antifungals first. Peptides support immune response.'),
('heavy_metal', 'Elevated mercury', 'High mercury levels in blood or urine challenge test', ARRAY['nad_plus','bpc157'], 1, 'NAD+ supports glutathione and methylation pathways needed for mercury detox. BPC-157 supports tissue healing.', 'PRIORITY: Complete heavy metal chelation protocol before starting peptide optimization. Metals impair peptide efficacy.'),
('heavy_metal', 'Elevated lead', 'High lead levels detected', ARRAY['nad_plus'], 1, 'NAD+ supports detoxification pathways. Focus on chelation first.', 'Complete chelation before peptide optimization. Lead impairs cellular function.'),
('viral', 'EBV reactivation', 'Elevated EBV VCA IgM or Early Antigen indicating reactivation', ARRAY['thymosin_a1','ll37','selank'], 4, 'Thymosin Alpha-1 enhances T-cell response to viruses. LL-37 has direct antiviral activity. Selank modulates immune-anxiety connection.', 'Address immune suppression factors. Optimize sleep and reduce stress.'),
('viral', 'CMV reactivation', 'Elevated CMV IgM or PCR indicating active replication', ARRAY['thymosin_a1','ll37'], 4, 'Thymosin Alpha-1 supports cytotoxic T-cell function. LL-37 has broad-spectrum antiviral properties.', 'Monitor viral load during treatment. Consider antiviral medication alongside.'),
('lyme', 'Borrelia positive', 'Active or persistent Lyme disease markers', ARRAY['thymosin_a1','ll37','bpc157','kpv'], 4, 'Immune support (Ta1, LL-37) plus anti-inflammatory healing (BPC-157, KPV) addresses both infection and tissue damage.', 'Antimicrobial treatment is primary. Peptides support immune response and reduce inflammation.'),
('sibo', 'SIBO positive', 'Positive lactulose or glucose breath test for SIBO', ARRAY['bpc157_oral','kpv','bpc157'], 3, 'Oral BPC-157 and KPV support gut mucosal healing. Prioritize gut healing before systemic peptide protocols.', 'IMPORTANT: Treat SIBO with antimicrobials/rifaximin first. Heal gut before adding systemic peptides that require good absorption.'),
('gut_zoomer', 'Intestinal permeability markers', 'Elevated anti-zonulin, anti-LPS, or anti-actin antibodies', ARRAY['bpc157','bpc157_oral','kpv'], 4, 'BPC-157 is the primary gut healing peptide. Oral form targets GI directly. KPV reduces intestinal inflammation.', 'Remove dietary triggers (gluten, dairy if sensitive). Address root cause of permeability.')
ON CONFLICT DO NOTHING;
