-- mRNA Vaccine Injury Therapy Protocols
-- 8 mechanism-based + 6 phenotype-based treatment protocols

CREATE TABLE IF NOT EXISTS public.vaccine_injury_protocols (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_type text NOT NULL CHECK (protocol_type IN ('mechanism', 'phenotype')),
  protocol_name text NOT NULL,
  description text,
  nutrients jsonb NOT NULL DEFAULT '[]',
  peptides jsonb DEFAULT '[]',
  lifestyle jsonb DEFAULT '[]',
  testing jsonb DEFAULT '[]',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  UNIQUE(protocol_type, protocol_name)
);

ALTER TABLE public.vaccine_injury_protocols ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read vaccine injury protocols"
  ON public.vaccine_injury_protocols FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can manage vaccine injury protocols"
  ON public.vaccine_injury_protocols FOR ALL USING (public.is_admin());

CREATE INDEX idx_vaccine_injury_type ON public.vaccine_injury_protocols(protocol_type);

-- 8 Mechanism-Based Protocols
INSERT INTO public.vaccine_injury_protocols (protocol_type, protocol_name, description, nutrients, peptides, lifestyle) VALUES

('mechanism', 'mitochondrial_support', 'Mitochondrial Support — for energy production dysfunction and electron transport chain impairment',
'[{"name":"CoQ10 (Ubiquinol)","mechanism":"Supports Complex I-III electron transfer; antioxidant","dose":"200-400 mg/day"},{"name":"Acetyl-L-Carnitine","mechanism":"Transports fatty acids into mitochondria; neuroprotective","dose":"1000-2000 mg/day"},{"name":"PQQ","mechanism":"Stimulates mitochondrial biogenesis","dose":"10-40 mg/day"},{"name":"Alpha Lipoic Acid","mechanism":"Antioxidant; regenerates other antioxidants","dose":"300-600 mg/day"},{"name":"Magnesium (glycinate/malate)","mechanism":"Required for ATP stability","dose":"200-400 mg/day"},{"name":"Curcumin (liposomal)","mechanism":"Reduces neuroinflammation and ROS","dose":"500-1000 mg/day"},{"name":"NAD+ Precursors (NMN or NR)","mechanism":"Supports Complex I and cellular energy","dose":"250-500 mg/day"}]'::jsonb,
'[{"name":"MOTS-c","mechanism":"AMPK activator, enhances Complex I and fat oxidation","dose":"5-10 mg SC 2-3x/week"},{"name":"SS-31 (Elamipretide)","mechanism":"Stabilizes cardiolipin in mitochondrial membranes","dose":"5 mg SC daily"},{"name":"KPV Peptide","mechanism":"Reduces inflammatory cytokines; calms immune activation","dose":"250-500 mcg daily"}]'::jsonb,
'[{"name":"Zone 2 Aerobic Training","mechanism":"Increases mitochondrial density and efficiency","dose":"20-30 min at 60-70% HRmax, 4x/week"},{"name":"Infrared Sauna","mechanism":"Activates heat shock proteins, enhances ATP production","dose":"15-30 min, 3-5x/week"},{"name":"Intermittent Fasting","mechanism":"Stimulates mitophagy and metabolic flexibility","dose":"14-16 hour daily fasting window"},{"name":"Cold Exposure","mechanism":"Triggers mitochondrial resilience via PGC1a","dose":"3-5 min cold plunge, 2-3x/week"},{"name":"Melatonin","mechanism":"Antioxidant; supports brain mitochondrial biogenesis","dose":"3-10 mg nightly"}]'::jsonb),

('mechanism', 'proteasome_stress', 'Proteasome-Mediated Stress — for protein misfolding and aggregation',
'[{"name":"NAC","mechanism":"Boosts glutathione; improves redox state for protein folding","dose":"900-1800 mg/day"},{"name":"Sulforaphane","mechanism":"Induces Nrf2, increases heat shock proteins and detox enzymes","dose":"100-200 umol/day"},{"name":"Curcumin (liposomal)","mechanism":"Anti-aggregation and proteasome-modulating effect","dose":"500-1000 mg/day"},{"name":"EGCG","mechanism":"Inhibits protein aggregation, modulates chaperones","dose":"300-500 mg/day"},{"name":"TUDCA","mechanism":"Improves ER stress, protein folding, reduces apoptosis","dose":"250-500 mg 2x/day"},{"name":"Ashwagandha","mechanism":"Supports HSP expression and stress response","dose":"500-600 mg/day"},{"name":"Resveratrol","mechanism":"Enhances proteasome activity and autophagy","dose":"100-250 mg/day"}]'::jsonb,
'[{"name":"Epitalon","mechanism":"Activates telomerase, regulates protein synthesis","dose":"10-20 mg SC 2-3x/week"},{"name":"Thymosin Alpha-1","mechanism":"Immune modulation, supports protein clearance","dose":"1.5 mg SC 2x/week"},{"name":"KPV peptide","mechanism":"Anti-inflammatory; modulates microglial protein stress","dose":"250-500 mcg daily"}]'::jsonb,
'[{"name":"Intermittent Fasting","mechanism":"Activates autophagy and clears damaged proteins","dose":"14-16 hr fasts, 5-6x/week"},{"name":"Sauna Therapy","mechanism":"Induces heat shock proteins; enhances protein folding","dose":"20-30 mins, 3-5x/week"},{"name":"Deep Sleep Optimization","mechanism":"Critical for protein repair, glymphatic clearance","dose":"Prioritize melatonin, consistent rhythm"}]'::jsonb),

('mechanism', 'transcriptomic_instability', 'Transcriptomic Instability — for RNA processing and ribosomal dysfunction',
'[{"name":"Zinc","mechanism":"Cofactor for RNA polymerase and ribosomal proteins","dose":"15-30 mg/day"},{"name":"Magnesium","mechanism":"Required for ribosomal integrity and ATP-dependent translation","dose":"200-400 mg/day"},{"name":"Methylated B Vitamins","mechanism":"Methyl donors for mRNA processing and DNA/RNA repair","dose":"B6: 25-50 mg; B12: 1000 mcg; Folate: 400-800 mcg/day"},{"name":"Selenium","mechanism":"Protects ribosomal machinery from oxidative damage","dose":"100-200 mcg/day"},{"name":"Glycine","mechanism":"Supports RNA methylation and glutathione synthesis","dose":"3-6 g/day"},{"name":"Berberine","mechanism":"AMPK activation reduces aberrant mRNA translation","dose":"200-500 mg BID"},{"name":"Quercetin","mechanism":"Reduces translation of inflammatory proteins","dose":"250-500 mg/day"}]'::jsonb,
'[{"name":"Epitalon","mechanism":"Enhances transcriptional fidelity and telomerase function","dose":"10-20 mg SC, 2-3x/week"},{"name":"GHK-Cu","mechanism":"RNA repair signaling, reduces oxidative RNA damage","dose":"5-10 mg SC daily or topical"}]'::jsonb,
'[{"name":"Time-Restricted Eating","mechanism":"Reduces ribosomal overload; supports autophagy","dose":"14-16 hrs daily fast"},{"name":"Infrared Sauna","mechanism":"Induces cellular stress recovery and chaperone expression","dose":"20-30 mins, 3-4x/week"},{"name":"Restorative Sleep","mechanism":"Deep sleep required for mRNA recycling","dose":"Fixed bedtime, full darkness, melatonin"}]'::jsonb),

('mechanism', 'systemic_inflammatory', 'Systemic Inflammatory Activation — for cytokine storm and immune dysregulation',
'[{"name":"Omega-3s (EPA/DHA)","mechanism":"Resolves inflammation, inhibits IL-1, IL-6, TNF-a","dose":"2-4 g EPA+DHA/day"},{"name":"Vitamin D3 + K2","mechanism":"Regulates T-reg cells, reduces autoimmune risk","dose":"D3: 5000-10000 IU/day"},{"name":"L-Glutamine","mechanism":"Supports GALT, restores mucosal immunity","dose":"5-10 g/day"},{"name":"NAC","mechanism":"Modulates T-cell and monocyte inflammatory activation","dose":"600-1200 mg BID"},{"name":"Curcumin (liposomal)","mechanism":"Broad-spectrum cytokine modulator; downregulates NF-kB + IL-6","dose":"500-1000 mg/day"},{"name":"Quercetin","mechanism":"Inhibits mast cells + T-cell cytokines","dose":"250-500 mg/day"},{"name":"Reishi Mushroom","mechanism":"Increases IL-10 and T-reg cells; balances Th1/Th2","dose":"500-1000 mg/day"}]'::jsonb,
'[{"name":"Thymosin Alpha-1","mechanism":"Enhances immune regulation, increases T-regs, suppresses IL-6","dose":"1.5 mg SC 2x/week"},{"name":"KPV Peptide","mechanism":"Reduces TNF-a and IFN-g; calms gut and systemic inflammation","dose":"250-500 mcg SC or oral daily"},{"name":"LDN","mechanism":"Modulates TLR4, microglia, and autoimmune cytokine cascades","dose":"1.5-4.5 mg nightly"}]'::jsonb,
'[{"name":"Vagal Nerve Stimulation","mechanism":"Promotes parasympathetic tone; reduces TNF, IL-6","dose":"Breathwork, humming, HRV daily"},{"name":"Zone 2 Movement","mechanism":"Suppresses chronic inflammation","dose":"30-40 min, 5-6 days/week"},{"name":"Anti-inflammatory Nutrition","mechanism":"Removes inflammatory triggers","dose":"AIP or Mediterranean-based diet"}]'::jsonb),

('mechanism', 'endothelial_dysfunction', 'Endothelial Dysfunction — for vascular damage and microclotting',
'[{"name":"L-Arginine or L-Citrulline","mechanism":"Substrates for nitric oxide synthesis; vasodilatory","dose":"Arginine: 2-6 g/day or Citrulline: 3-5 g/day"},{"name":"Vitamin K2 (MK-7)","mechanism":"Regulates arterial calcification and vascular elasticity","dose":"100-300 mcg/day"},{"name":"Vitamin C","mechanism":"Collagen support, endothelial integrity, antioxidant","dose":"1-3 g/day orally or IV"},{"name":"Omega-3s","mechanism":"Resolves inflammation, reduces platelet aggregation","dose":"2-4 g EPA+DHA/day"},{"name":"Nattokinase","mechanism":"Fibrinolytic enzyme that breaks down microclots","dose":"100-200 mg/day empty stomach"},{"name":"CoQ10 (Ubiquinol)","mechanism":"Mitochondrial support for endothelial energy","dose":"200-400 mg/day"},{"name":"Beetroot","mechanism":"Increases NO via dietary nitrates","dose":"4-8 oz juice or 4-6 g powder/day"}]'::jsonb,
'[{"name":"BPC-157","mechanism":"Promotes angiogenesis, collagen repair, vascular healing","dose":"200-500 mcg SC or oral daily"},{"name":"Thymosin Beta-4","mechanism":"Stimulates endothelial progenitor cells, tissue regeneration","dose":"2-5 mg SC 2-3x/week"},{"name":"Glycine","mechanism":"Glycocalyx and collagen repair; inhibits platelet aggregation","dose":"3-6 g/day"}]'::jsonb,
'[{"name":"Daily Walking (Zone 2)","mechanism":"Increases nitric oxide, improves endothelial shear stress","dose":"30-45 min, 5-6x/week"},{"name":"Infrared Sauna","mechanism":"Improves endothelial vasodilation and HSP-mediated repair","dose":"20-30 min, 3-4x/week"},{"name":"Sleep Optimization","mechanism":"Endothelial repair occurs during deep sleep","dose":"Prioritize sleep hygiene and circadian alignment"}]'::jsonb),

('mechanism', 'proliferative_signaling', 'Proliferative Signaling & Tumor Surveillance — for MYC/mTOR dysregulation and p53 impairment',
'[{"name":"Sulforaphane","mechanism":"Inhibits MYC expression, activates Nrf2","dose":"60-100 mg/day"},{"name":"Pterostilbene/Resveratrol","mechanism":"Activates SIRT1 and p53, supports DNA repair","dose":"100-250 mg/day"},{"name":"Curcumin (liposomal)","mechanism":"Downregulates MYC, NF-kB, and mTOR","dose":"500-1000 mg/day"},{"name":"NAC","mechanism":"Precursor to glutathione; protects DNA and regulates cell cycle","dose":"600-1200 mg BID"},{"name":"Melatonin","mechanism":"Enhances p53 signaling, protects against DNA damage","dose":"3-20 mg at night"},{"name":"EGCG","mechanism":"Downregulates MYC, inhibits angiogenesis and telomerase","dose":"300-600 mg/day"},{"name":"Zinc + Selenium","mechanism":"Cofactors for DNA repair enzymes and p53 stabilization","dose":"Zinc: 25-30 mg; Se: 200 mcg/day"}]'::jsonb,
'[{"name":"Epitalon","mechanism":"Activates telomerase, improves DNA repair fidelity","dose":"10-20 mg SC, 2-3x/week"},{"name":"Thymosin Alpha-1","mechanism":"Stimulates NK cell activity, CD8+ T-cell function","dose":"1.5 mg SC 2x/week"},{"name":"GHK-Cu","mechanism":"Activates DNA repair and anti-tumor signaling genes","dose":"5-10 mg SC daily or topical"}]'::jsonb,
'[{"name":"Intermittent Fasting","mechanism":"Decreases IGF-1 and mTOR, increases autophagy","dose":"14-16 hr fasts, 5-6 days/week"},{"name":"Exercise (HIIT + Zone 2)","mechanism":"Increases immune surveillance (NK cells), reduces IGF-1","dose":"30-45 min, 5-6 days/week"},{"name":"Environmental Toxin Reduction","mechanism":"Avoid xenoestrogens, plastics, glyphosate, heavy metals","dose":"Filtered water, clean food"}]'::jsonb),

('mechanism', 'epigenetic_remodeling', 'Epigenetic Remodeling & Chromatin Dysregulation — for methylation and histone modification disruption',
'[{"name":"Methylated B12","mechanism":"Supports SAMe cycle and DNA methylation fidelity","dose":"1000-5000 mcg/day"},{"name":"5-MTHF (Methylfolate)","mechanism":"Donates methyl groups to DNA methyltransferase pathways","dose":"400-800 mcg/day"},{"name":"Vitamin B6 (P5P)","mechanism":"Supports transsulfuration + neurotransmitter methylation","dose":"25-50 mg/day"},{"name":"Betaine (TMG)","mechanism":"Recycles homocysteine to methionine","dose":"500-1000 mg/day"},{"name":"Sulforaphane","mechanism":"Inhibits DNMTs, promotes detox gene expression via Nrf2","dose":"60-100 mg/day"},{"name":"Resveratrol","mechanism":"Activates SIRT1, regulates histone acetylation","dose":"100-250 mg/day"},{"name":"Curcumin","mechanism":"HDAC inhibitor, anti-inflammatory epigenetic regulator","dose":"500-1000 mg/day"}]'::jsonb,
'[{"name":"Epitalon","mechanism":"Activates telomerase, regulates circadian gene expression","dose":"10-20 mg SC, 2-3x/week"},{"name":"GHK-Cu","mechanism":"Regulates ~4000 genes including wound healing and anti-tumor","dose":"5-10 mg SC or topical daily"},{"name":"Melatonin (high dose)","mechanism":"Epigenetic regulator of circadian, p53, and tumor suppressor genes","dose":"10-20 mg nightly"}]'::jsonb,
'[{"name":"Circadian Rhythm Optimization","mechanism":"Epigenetically regulates ~10% of human genes","dose":"Morning light, consistent bedtime"},{"name":"Intermittent Fasting","mechanism":"Promotes epigenetic remodeling and histone acetylation resets","dose":"14-16 hr daily fast"},{"name":"Red/NIR Light Therapy","mechanism":"Modulates gene expression via mitochondrial-nuclear crosstalk","dose":"10-20 min, 3-5x/week"}]'::jsonb),

('mechanism', 'genomic_instability', 'Genomic Instability and DNA Repair — for DNA damage and impaired repair mechanisms',
'[{"name":"NAC","mechanism":"Precursor to glutathione; protects nuclear and mitochondrial DNA from ROS","dose":"600-1200 mg BID"},{"name":"Alpha-Lipoic Acid","mechanism":"Recycles antioxidants and supports redox-based repair enzyme activity","dose":"300-600 mg/day"},{"name":"L-Carnosine","mechanism":"Scavenges DNA-damaging aldehydes and reactive carbonyl species","dose":"500-1000 mg/day"},{"name":"Methylated B12 + Folate","mechanism":"Required for nucleotide synthesis and methylation of DNA repair genes","dose":"B12: 1000-5000 mcg; Folate: 400-800 mcg/day"},{"name":"Zinc + Selenium","mechanism":"Cofactors for DNA repair enzymes (PARP, SOD, p53)","dose":"Zinc: 25-30 mg; Se: 200 mcg/day"},{"name":"Curcumin","mechanism":"Suppresses STING activation, downregulates NF-kB","dose":"500-1000 mg/day"},{"name":"Spermidine","mechanism":"Promotes autophagy, enhances DNA repair enzyme expression","dose":"1-2 mg/day"}]'::jsonb,
'[{"name":"Epitalon","mechanism":"Activates telomerase, protects telomeres, enhances genome stability","dose":"10-20 mg SC, 2-3x/week"},{"name":"GHK-Cu","mechanism":"Activates DNA repair genes, supports anti-cancer transcriptome","dose":"5-10 mg SC or topical daily"},{"name":"Thymosin Beta-4","mechanism":"Supports actin repair, facilitates tissue regeneration","dose":"2-5 mg SC 2-3x/week"},{"name":"IV NAD+ or NMN/NR","mechanism":"Supports mitochondrial-nuclear signaling, enhances SIRT-mediated DNA repair","dose":"IV: 250-500 mg weekly; NMN: 250-500 mg/day"}]'::jsonb,
'[{"name":"Intermittent Fasting","mechanism":"Reduces DNA replication stress, activates autophagy and repair enzymes","dose":"14-16 hrs/day, 5-6x/week"},{"name":"Photobiomodulation","mechanism":"Enhances mitochondrial genome stability, activates Nrf2 and p53","dose":"10-20 min, 3-5x/week"},{"name":"Sleep Optimization","mechanism":"Crucial for DNA repair enzyme expression and circadian repair gene alignment","dose":"7-8 hrs/night + fixed bedtime"}]'::jsonb)

ON CONFLICT (protocol_type, protocol_name) DO NOTHING;

-- 6 Phenotype-Based Protocols
INSERT INTO public.vaccine_injury_protocols (protocol_type, protocol_name, description, nutrients, peptides, lifestyle) VALUES

('phenotype', 'neurologic_autonomic', 'Neurologic & Autonomic — brain fog, neuropathy, POTS, dysautonomia, cognitive decline',
'[{"name":"LDN","mechanism":"Microglial regulation, immune modulation","dose":"1.5-4.5 mg nightly"},{"name":"Acetyl-L-carnitine","mechanism":"Mitochondrial + cognitive enhancement","dose":"500-1500 mg/day"},{"name":"Magnesium threonate","mechanism":"CNS penetration, neuronal calming","dose":"1-2 g at night"},{"name":"Melatonin","mechanism":"Anti-neuroinflammatory, circadian reset","dose":"5-10 mg nightly"},{"name":"Nigella sativa","mechanism":"Neuroprotective, antioxidant, anti-inflammatory","dose":"500-1000 mg BID"}]'::jsonb,
'[{"name":"KPV peptide","mechanism":"Anti-inflammatory, gut-brain axis modulator","dose":"250-500 mcg SC or oral daily"},{"name":"BPC-157","mechanism":"Blood-brain barrier repair, autonomic support","dose":"200-500 mcg SC daily"}]'::jsonb,
'[{"name":"Vagal nerve exercises","mechanism":"Parasympathetic tone restoration","dose":"Breathwork, humming, cold face immersion daily"},{"name":"Grounding/earthing","mechanism":"Reduces inflammatory charge","dose":"20-30 min barefoot contact daily"}]'::jsonb),

('phenotype', 'fatigue_mitochondrial', 'Fatigue & Mitochondrial — chronic fatigue, exercise intolerance, post-exertional malaise',
'[{"name":"CoQ10 (Ubiquinol)","mechanism":"ETC Complex I/III support","dose":"200-400 mg/day"},{"name":"PQQ","mechanism":"Mitochondrial biogenesis","dose":"10-40 mg/day"},{"name":"Alpha-lipoic acid","mechanism":"Mitochondrial antioxidant","dose":"300-600 mg/day"},{"name":"NAD+ precursors (NMN/NR)","mechanism":"Sirtuin and mitochondrial repair","dose":"250-500 mg/day"}]'::jsonb,
'[{"name":"MOTS-c","mechanism":"AMPK activation, metabolic reset","dose":"5-10 mg SC 2-3x/week"}]'::jsonb,
'[{"name":"Intermittent fasting","mechanism":"Promotes mitophagy","dose":"14-16 hrs fasting, 5-6x/week"},{"name":"Zone 2 exercise","mechanism":"Mitochondrial density","dose":"20-30 min, 4x/week, very gentle start"}]'::jsonb),

('phenotype', 'clotting_vascular', 'Clotting & Vascular — microclotting, D-dimer elevation, vascular inflammation',
'[{"name":"Nattokinase","mechanism":"Fibrinolytic enzyme, spike cleavage","dose":"100-200 mg/day empty stomach"},{"name":"Lumbrokinase","mechanism":"Microclot dissolver","dose":"20 mg 2x/day"},{"name":"Omega-3 (EPA/DHA)","mechanism":"Anti-inflammatory, endothelial support","dose":"2-4 g/day"},{"name":"Hydration + electrolytes","mechanism":"Microvascular flow","dose":"2-3 L fluid/day + trace minerals"}]'::jsonb,
'[{"name":"BPC-157","mechanism":"Vascular healing","dose":"200-500 mcg SC daily"},{"name":"Therapeutic plasma exchange","mechanism":"Spike/autoantibody clearance","dose":"3-5 sessions for severe cases"}]'::jsonb,
'[{"name":"Gentle movement","mechanism":"Prevents stasis","dose":"Walking 20-30 min daily"},{"name":"Compression","mechanism":"Supports venous return","dose":"Graduated compression stockings if tolerated"}]'::jsonb),

('phenotype', 'endocrine_menstrual', 'Endocrine & Menstrual — cycle disruption, hormone dysregulation, thyroid changes',
'[{"name":"Melatonin","mechanism":"HPO axis stabilization, antioxidant","dose":"3-10 mg nightly"},{"name":"Vitex (chaste tree)","mechanism":"Hormonal modulation for low progesterone","dose":"300-600 mg/day"},{"name":"DHEA","mechanism":"Hormone precursor, neurosteroid support","dose":"5-25 mg/day based on labs"},{"name":"Adaptogens","mechanism":"Adrenal-hormone rhythm support","dose":"Rhodiola 200-400 mg; Ashwagandha 500 mg/day"},{"name":"Magnesium glycinate","mechanism":"PMS, sleep, adrenal support","dose":"300-400 mg/day"}]'::jsonb,
'[]'::jsonb,
'[{"name":"Circadian consistency","mechanism":"Hormone rhythm restoration","dose":"Fixed sleep-wake schedule, morning light"},{"name":"Stress reduction","mechanism":"HPA axis recovery","dose":"Daily breathwork, meditation"}]'::jsonb),

('phenotype', 'musculoskeletal_pain', 'Musculoskeletal & Pain — joint pain, myalgia, fibromyalgia-like symptoms',
'[{"name":"Curcumin (liposomal)","mechanism":"NF-kB / IL-6 inhibition","dose":"500-1000 mg BID"},{"name":"Boswellia","mechanism":"5-LOX inhibition, anti-inflammatory","dose":"300-600 mg/day"},{"name":"Omega-3s","mechanism":"Reduce joint inflammation","dose":"2-4 g/day"},{"name":"Magnesium","mechanism":"Muscle relaxation, pain modulation","dose":"300-400 mg/day"}]'::jsonb,
'[{"name":"LL-37","mechanism":"Innate immune reset","dose":"100-300 mcg SC 2-3x/week for advanced cases"},{"name":"BPC-157","mechanism":"Tissue repair, anti-inflammatory","dose":"200-500 mcg SC daily"}]'::jsonb,
'[{"name":"Epsom salt baths","mechanism":"Magnesium sulfate absorption, muscle relaxation","dose":"2-3x/week"},{"name":"HBOT","mechanism":"Tissue oxygenation","dose":"1.5-2.0 ATA, 60-90 min, 2-3x/week"}]'::jsonb),

('phenotype', 'immune_dysregulation', 'Immune Dysregulation — reactivated viruses, new autoimmunity, MCAS, histamine intolerance',
'[{"name":"LDN","mechanism":"Modulates T-regs, reduces cytokine output","dose":"1.5-4.5 mg nightly"},{"name":"Quercetin","mechanism":"Stabilizes mast cells","dose":"250-500 mg BID"},{"name":"DAO enzyme","mechanism":"Breaks down histamine (if histamine-sensitive)","dose":"10000-20000 HDU pre-meal"},{"name":"Vitamin D3 + K2","mechanism":"T-reg upregulation","dose":"D3: 5000-10000 IU; K2: 100-300 mcg/day"},{"name":"Selenium + Zinc","mechanism":"Autoimmune support, redox balance","dose":"Se: 200 mcg; Zn: 25-30 mg/day"},{"name":"Nigella sativa","mechanism":"Anti-inflammatory, Th1/Th2 balance, mast cell stabilizer","dose":"500-1000 mg BID"}]'::jsonb,
'[{"name":"Thymosin Alpha-1","mechanism":"Immune modulation, enhances immune surveillance","dose":"1.5 mg SC 2x/week"}]'::jsonb,
'[{"name":"Anti-inflammatory diet","mechanism":"Removes immune triggers","dose":"AIP or low-histamine protocol"},{"name":"Stress management","mechanism":"Reduces immune dysregulation","dose":"Daily HRV training, breathwork"}]'::jsonb)

ON CONFLICT (protocol_type, protocol_name) DO NOTHING;
